<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="CSS/headerStyle.css" />
    <title><?php echo $view->pageTitle; ?></title>
</head>

<body>
<nav class="navbar">
    <!-- Website logo -->
    <div class="logo"><img src="Images/sts-logo.png" width="90" alt="STS Logo"></div>
    <!-- navigation menu-->
    <ul class="nav-links">
        <!-- navigation menus -->
        <div class="menu">

                <li><a href="record.php">Records</a></li>
                <li><a href="form.php">Create new form</a></li>
                <li><a href="logout.php">Logout</a></li>

        </div>

    </ul>
    </div>
</nav>
</body>
</html>


