<?php require('template/headerEx.phtml') ?>
<link rel="stylesheet" href="CSS/loginStyle.css" />

<!-- Title of page -->
<head>
    <title>Sign in</title>
</head>

<body>

<div class="main">
    <!-- Heading -->
    <p class="sign" align="center">Sign In</p>

    <form class="form1"   method="post">
        <!-- User input -->
        <input class="details" type="text" align="center" placeholder="Username" name="username" required>
        <input class="pass" type="password" align="center" placeholder="Password" name="password" required>
        <!-- logging in button -->
        <button class="submit" type="submit" align="center">Sign In</button>
    </form>
</div>

</body>
